-- AlterTable
ALTER TABLE "User" ADD COLUMN     "roleId" INTEGER NOT NULL DEFAULT 2;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
